@startuml

skinparam componentStyle uml2

package se.citerus.dddsample.domain.model.InformacionCatastral {
	package "'InformacionCatastral' Aggregate" <<Rectangle>> {
		class DetallesLote <<(V,DarkSeaGreen) Value Object>> {
		}
		class DetallesEdificio <<(V,DarkSeaGreen) Value Object>> {
		}
		class DetallesPiso <<(V,DarkSeaGreen) Value Object>> {
		}
		class Parcela <<(E,DarkSeaGreen) Entity>> {
		}
		class Lote <<(E,DarkSeaGreen) Entity>> {
		}
		class Edificio <<(E,DarkSeaGreen) Entity>> {
		}
		class Piso <<(E,DarkSeaGreen) Entity>> {
		}
		class IntegracionInformacion <<(S,DarkSeaGreen) Service>> {
		}
	}
}


@enduml
