@startuml

skinparam componentStyle uml2

package se.citerus.dddsample.domain.model.InformacionContractual {
	package "'InformacionContractual' Aggregate" <<Rectangle>> {
		class MovimientoContrato <<(V,DarkSeaGreen) Value Object>> {
		}
		class InformacionCompania <<(V,DarkSeaGreen) Value Object>> {
		}
		class ContratoDigital <<(V,DarkSeaGreen) Value Object>> {
		}
		class EmpresaContratosAlpes <<(E,DarkSeaGreen) Entity>> {
		}
		class EmpresaListadosPropiedades <<(E,DarkSeaGreen) Entity>> {
		}
	}
}


@enduml
