@startuml

skinparam componentStyle uml2

package se.citerus.dddsample.domain.model.InformacionGeoespacialYAlojamiento {
	package "'InformacionGeoespacial' Aggregate" <<Rectangle>> {
		class AreaLote <<(V,DarkSeaGreen) Value Object>> {
		}
		class Coordenadas <<(V,DarkSeaGreen) Value Object>> {
		}
		class Poligono <<(V,DarkSeaGreen) Value Object>> {
		}
		class Propiedad <<(E,DarkSeaGreen) Entity>> {
		}
		class Edificio <<(E,DarkSeaGreen) Entity>> {
		}
		class Direccion <<(E,DarkSeaGreen) Entity>> {
		}
		class GoogleMaps <<(S,DarkSeaGreen) Service>> {
		}
		class BingMaps <<(S,DarkSeaGreen) Service>> {
		}
		class OpenStreetMap <<(S,DarkSeaGreen) Service>> {
		}
	}
}


@enduml
